name: bito_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.6.0
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  widgetbook_annotation: ^3.1.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true
